name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate scripts
        shell: powershell
        run: .\tests\Test-Scripts.ps1

      - name: Validate scripts with PowerShell 7
        shell: pwsh
        run: .\tests\Test-Scripts.ps1
